apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-app
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: test-app
        persistentVolumeClaim:
          claimName: pvc-app
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_PASSWORD
          # value: 'p4ssw0rd'
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          # value: 'postgres'
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_DB
          # value: 'postgres'
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "600m"
            memory: "512Mi"
        ports:
        - containerPort: 3036
          name: http-web-svc
        volumeMounts:
        - name: test-app
          mountPath: /var/lib/postgresql/data

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service # use config map
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 5432
    targetPort: 5432
